<script setup lang="ts">
import { reactive, ref } from 'vue';import { useRouter } from 'vue-router';import TopBar from '@/components/ui/TopBar.vue';import { useEventsStore } from '@/stores/events';import { useSessionStore } from '@/stores/session';import type { EventKind } from '@/types/domain';import { telegram } from '@/services/telegram';
const router=useRouter(),events=useEventsStore(),session=useSessionStore();const busy=ref(false);const error=ref('');
const districts:Record<string,[number,number]>={'Центр':[53.9006,27.5590],'Немига':[53.9052,27.5535],'Зыбицкая':[53.9050,27.5587],'Октябрьская':[53.9023,27.5619],'Верхний город':[53.9040,27.5568],'Комаровка':[53.9165,27.5770],'Уручье':[53.9382,27.6550],'Восток':[53.9230,27.6104],'Серебрянка':[53.8799,27.6200],'Малиновка':[53.8507,27.4742],'Лошица':[53.8517,27.5794]};
const now=new Date(Date.now()+60*60*1000);const local=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);
const form=reactive({title:'',description:'',kind:'party' as EventKind,district:'Центр',publicLocation:'Центр, Минск',privateAddress:'',startLocal:local,price:0,capacity:12,age:'18+',tags:'музыка, новые знакомства',requiresApproval:true});
async function submit(){if(session.publicOnly){error.value='Создание событий доступно внутри Telegram.';return}busy.value=true;error.value='';try{const [lat,lng]=districts[form.district]||districts['Центр'];telegram.haptic('medium');const e=await events.create({title:form.title,description:form.description,kind:form.kind,emoji:'✨',vibe:'НОВОЕ',district:form.district,publicLocation:form.publicLocation||form.district,privateAddress:form.privateAddress,lat,lng,startAt:new Date(form.startLocal).toISOString(),endAt:null,price:Number(form.price),capacity:Number(form.capacity),age:form.age,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),schedule:[],requiresApproval:form.requiresApproval});telegram.notify('success');router.replace(`/manage/${e.id}`);}catch(e){error.value=e instanceof Error?e.message:'Не удалось создать событие.'}finally{busy.value=false}}
</script>
<template><section class="screen"><TopBar/><header class="page-title"><small>СОЗДАТЬ</small><h1>Собери свой вечер</h1><p>Событие сразу появится в общей ленте и на карте.</p></header><form class="form-card" @submit.prevent="submit"><label>Название<input v-model="form.title" minlength="3" maxlength="90" required placeholder="Квартира на Немиге"></label><label>Описание<textarea v-model="form.description" minlength="10" required placeholder="Что будет происходить, кого ждёте, какой вайб"></textarea></label><div class="form-grid"><label>Тип<select v-model="form.kind"><option value="party">Тусовка</option><option value="home">Домашняя</option><option value="bar">Бар</option><option value="music">Музыка</option><option value="games">Игры</option><option value="social">Знакомства</option><option value="spontaneous">Спонтанно</option></select></label><label>Район<select v-model="form.district"><option v-for="(_,d) in districts" :key="d">{{d}}</option></select></label></div><label>Когда<input type="datetime-local" v-model="form.startLocal" required></label><div class="form-grid"><label>Цена, руб.<input type="number" min="0" step="1" v-model.number="form.price"></label><label>Мест<input type="number" min="2" max="5000" v-model.number="form.capacity"></label></div><label>Публичная локация<input v-model="form.publicLocation"></label><label>Точный адрес <small>виден только принятым гостям</small><input v-model="form.privateAddress" placeholder="ул. …"></label><label>Теги<input v-model="form.tags"></label><label class="check"><input type="checkbox" v-model="form.requiresApproval"> Принимать гостей вручную</label><p v-if="error" class="error">{{error}}</p><button class="primary" :disabled="busy">{{busy?'Публикуем…':'Опубликовать событие'}}</button></form></section></template>
