<script setup lang="ts">
import { onMounted, computed, ref } from 'vue';
import { useRoute } from 'vue-router';
import TopBar from '@/components/ui/TopBar.vue';
import Avatar from '@/components/ui/Avatar.vue';
import EmptyState from '@/components/ui/EmptyState.vue';
import { useEventsStore } from '@/stores/events';
import { useInboxStore } from '@/stores/inbox';
import { telegram } from '@/services/telegram';
const route=useRoute(),events=useEventsStore(),inbox=useInboxStore(),id=String(route.params.id),uploading=ref(false),fileInput=ref<HTMLInputElement|null>(null);
onMounted(async()=>{await Promise.all([events.loadMy(),inbox.load(),events.loadMembers(id)]);const e=events.my.find(x=>x.id===id);if(e)events.current=e});const e=computed(()=>events.my.find(x=>x.id===id)||events.current);const reqs=computed(()=>inbox.incoming.filter(r=>r.event_id===id));
async function edit(){if(!e.value)return;const title=prompt('Название:',e.value.title);if(title===null)return;const description=prompt('Описание:',e.value.desc);if(description===null)return;await events.update(id,{title,description});telegram.notify('success');await events.loadMy()}
async function uploadCover(ev:Event){const input=ev.target as HTMLInputElement,file=input.files?.[0];if(!file)return;uploading.value=true;try{await events.uploadCover(id,file);telegram.notify('success')}finally{uploading.value=false;input.value=''}}
</script>
<template><section class="screen"><TopBar back title="Управление"/><div v-if="e" class="manage"><header class="page-title"><small>ЦЕНТР УПРАВЛЕНИЯ</small><h1>{{e.title}}</h1><p>{{e.people}} / {{e.capacity}} участников · {{reqs.filter(r=>r.status==='pending').length}} новых заявок</p></header><div class="action-row"><RouterLink class="primary link-button" :to="`/chat/${id}`">Чат</RouterLink><button class="secondary" @click="edit">Редактировать</button></div><input ref="fileInput" class="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp,image/avif" @change="uploadCover"><button class="secondary manage-cover-button" :disabled="uploading" @click="fileInput?.click()">{{uploading?'Загружаем…':'Обновить обложку'}}</button><section class="section"><div class="section-head"><h2>Новые заявки</h2></div><div class="stack"><RouterLink v-for="r in reqs" :key="r.id" :to="`/request/${r.id}`" class="request-row"><div><b>{{r.applicant?.display_name}}</b><small>{{r.note||'Без сообщения'}}</small><span>{{r.status}}</span></div></RouterLink><EmptyState v-if="!reqs.length" icon="inbox" title="Новых заявок нет" text="Когда кто-то захочет присоединиться, заявка появится здесь автоматически."/></div></section><section class="section"><div class="section-head"><h2>Участники</h2></div><div class="stack"><article v-for="m in events.members" :key="m.user_id" class="member-row"><Avatar :name="m.user?.display_name||'Гость'" :src="m.user?.avatar_url"/><div><b>{{m.user?.display_name}}</b><small>{{m.role}}</small></div><button v-if="m.role!=='organizer'" @click="events.removeMember(id,m.user_id)">Удалить</button></article></div></section></div></section></template>
