<script setup lang="ts">
import { computed, ref } from 'vue';import VibeMap from '@/components/map/VibeMap.vue';import Icon from '@/components/ui/Icon.vue';import { useEventsStore } from '@/stores/events';import { formatTime } from '@/services/format';import { eventCover } from '@/services/covers';import type { EventItem } from '@/types/domain';
const events=useEventsStore();const selected=ref<EventItem|null>(null),filter=ref<'all'|'home'|'free'|'now'>('all'),map=ref<{ locate: () => void; zoomIn:()=>void; zoomOut:()=>void; reset:()=>void }|null>(null);
const points=computed(()=>events.items.filter(e=>filter.value==='all'?true:filter.value==='home'?e.kind==='home':filter.value==='free'?e.price===0:Math.abs(new Date(e.startAt).getTime()-Date.now())<4*3600000));
</script>
<template><section class="map-page">
  <VibeMap ref="map" :events="points" @select="selected=$event"/>
  <div class="map-chrome"><div class="map-topline"><div><small>МИНСК · {{points.length}} СОБЫТИЙ</small><h1>Карта вечера</h1></div><button class="map-locate" @click="map?.locate()"><Icon name="pin"/></button></div><div class="map-filters"><button :class="{active:filter==='now'}" @click="filter='now'">Сейчас</button><button :class="{active:filter==='all'}" @click="filter='all'">Сегодня</button><button :class="{active:filter==='home'}" @click="filter='home'">Домашние</button><button :class="{active:filter==='free'}" @click="filter='free'">Бесплатно</button></div></div>
  <div class="map-controls"><button @click="map?.zoomIn()">+</button><button @click="map?.zoomOut()">−</button><button @click="map?.reset()"><Icon name="spark" :size="18"/></button></div>
  <Transition name="sheet"><div v-if="selected" class="map-sheet"><button class="sheet-close" @click="selected=null">×</button><div class="map-sheet-cover" :style="{backgroundImage:`url('${eventCover(selected.kind,selected.coverUrl)}')`}"></div><div class="map-sheet-copy"><small>{{selected.district}} · {{formatTime(selected.startAt)}}</small><h2>{{selected.title}}</h2><p>{{selected.people}} идут · {{Math.max(0,selected.capacity-selected.people)}} мест</p><RouterLink :to="`/event/${selected.id}`" class="primary link-button">Открыть событие</RouterLink></div></div></Transition>
</section></template>
