import { Hono } from 'hono';
import { cors } from 'hono/cors';
import type { AppEnv } from './types';
import { createDb } from './lib/supabase';import { currentUser } from './lib/auth';import { errorResponse, HttpError } from './lib/errors';import { userDto } from './lib/dto';import { appDeepLink, notify } from './lib/telegram';import { realtime } from './lib/realtime';import { createRealtimeTicket, verifyRealtimeTicket } from './lib/realtime-token';
import * as events from './services/events';import * as requests from './services/requests';import * as chat from './services/chat';import * as users from './services/users';export { RealtimeHub } from './realtime';
import { createEventSchema, joinSchema, messageSchema, profileSchema, reportSchema, resolveSchema, statusSchema, updateEventSchema } from './schemas/input';

const app=new Hono<AppEnv>();
app.use('/api/*',cors({origin:'*',allowHeaders:['content-type','x-telegram-init-data','x-vibe-dev-user'],allowMethods:['GET','POST','PATCH','DELETE','OPTIONS']}));
app.onError((err,c)=>errorResponse(c,err));

const body=async <T>(c:any,schema:any):Promise<T>=>{const parsed=schema.safeParse(await c.req.json().catch(()=>({})));if(!parsed.success)throw new HttpError(422,'Проверьте заполнение формы.',parsed.error.flatten());return parsed.data as T};

app.get('/api/config',c=>c.json({ok:true,config:{appUrl:c.env.APP_URL||'',mapEngine:'maplibre-osm'}}));
app.get('/api/realtime/token',async c=>{const db=createDb(c.env),user=await currentUser(c,db,true);return c.json({ok:true,...createRealtimeTicket(user.id,c.env.TELEGRAM_BOT_TOKEN)})});
app.get('/api/realtime',async c=>{if(c.req.header('Upgrade')?.toLowerCase()!=='websocket')throw new HttpError(426,'Требуется WebSocket-соединение.');const token=c.req.query('token')||'';const ticket=verifyRealtimeTicket(token,c.env.TELEGRAM_BOT_TOKEN);const id=c.env.REALTIME.idFromName('vibe-main'),stub=c.env.REALTIME.get(id);const headers=new Headers(c.req.raw.headers);headers.set('x-vibe-user-id',ticket.uid);return stub.fetch(new Request('https://realtime.internal/connect',{method:'GET',headers}))});
app.get('/api/events',async c=>{const db=createDb(c.env),user=await currentUser(c,db,false);return c.json({ok:true,events:await events.publicEvents(db,user)})});
app.get('/api/session',async c=>{const db=createDb(c.env),user=await currentUser(c,db,true);const own=await db.from('events').select('id').eq('organizer_id',user.id);if(own.error)throw own.error;const ids=(own.data||[]).map((x:any)=>x.id);const pending=ids.length?await db.from('event_requests').select('id',{count:'exact',head:true}).in('event_id',ids).eq('status','pending'):{count:0};const notes=await db.from('notifications').select('id',{count:'exact',head:true}).eq('user_id',user.id).is('read_at',null);const bot=(c.env.TELEGRAM_BOT_USERNAME||'').replace(/^@/,'');const short=(c.env.TELEGRAM_APP_SHORT_NAME||'').replace(/^\//,'');return c.json({ok:true,user:userDto(user),stats:{myEvents:ids.length,pendingRequests:pending.count||0,unreadNotifications:notes.count||0},config:{appLinkBase:bot?(short?`https://t.me/${bot}/${short}`:`https://t.me/${bot}`):'',appUrl:c.env.APP_URL||'',mapEngine:'maplibre-osm'}})});

app.get('/api/events/:id',async c=>{const db=createDb(c.env),user=await currentUser(c,db,false);return c.json({ok:true,event:await events.oneEvent(db,user,c.req.param('id'))})});
app.get('/api/me/events',async c=>{const db=createDb(c.env),user=await currentUser(c,db);return c.json({ok:true,events:await events.myEvents(db,user)})});
app.post('/api/events',async c=>{const db=createDb(c.env),user=await currentUser(c,db),input=await body<any>(c,createEventSchema);const event=await events.createEvent(db,user,input);await realtime.all(c.env,{type:'event.created',eventId:event.id});await realtime.users(c.env,[user.id],{type:'me.events.changed',eventId:event.id});return c.json({ok:true,event},201)});
app.patch('/api/events/:id',async c=>{const db=createDb(c.env),user=await currentUser(c,db),input=await body<any>(c,updateEventSchema),eventId=c.req.param('id');const event=await events.updateEvent(db,user,eventId,input);await realtime.all(c.env,{type:'event.updated',eventId});await realtime.users(c.env,[user.id],{type:'me.events.changed',eventId});const members=await db.from('event_members').select('user_id').eq('event_id',eventId).neq('user_id',user.id);if(!members.error){for(const m of members.data||[])await notify(db,c.env,{userId:m.user_id,actorId:user.id,eventId,type:'event_updated',title:'Событие обновлено',body:`Организатор изменил «${event.title}».`})}return c.json({ok:true,event})});
app.post('/api/events/:id/status',async c=>{const db=createDb(c.env),user=await currentUser(c,db),input=await body<any>(c,statusSchema),eventId=c.req.param('id');await events.setStatus(db,user,eventId,input.status);await realtime.all(c.env,{type:'event.updated',eventId});await realtime.users(c.env,[user.id],{type:'me.events.changed',eventId});return c.json({ok:true})});
app.post('/api/events/:id/join',async c=>{const db=createDb(c.env),user=await currentUser(c,db),input=await body<any>(c,joinSchema),eventId=c.req.param('id');const owner=await db.from('events').select('organizer_id').eq('id',eventId).single();if(owner.error)throw owner.error;const request=await requests.joinEvent(db,c.env,user,eventId,input.note);await realtime.users(c.env,[user.id,owner.data.organizer_id],{type:'request.changed',eventId,requestId:request.id});if(request.status==='accepted')await realtime.all(c.env,{type:'event.updated',eventId});return c.json({ok:true,request})});
app.delete('/api/events/:id/request',async c=>{const db=createDb(c.env),user=await currentUser(c,db),eventId=c.req.param('id');const owner=await db.from('events').select('organizer_id').eq('id',eventId).single();if(owner.error)throw owner.error;await requests.cancelRequest(db,user,eventId);await realtime.users(c.env,[user.id,owner.data.organizer_id],{type:'request.changed',eventId});return c.json({ok:true})});
app.get('/api/events/:id/members',async c=>{const db=createDb(c.env),user=await currentUser(c,db);return c.json({ok:true,members:await events.members(db,user,c.req.param('id'))})});
app.post('/api/events/:id/leave',async c=>{const db=createDb(c.env),user=await currentUser(c,db),eventId=c.req.param('id');const owner=await db.from('events').select('organizer_id').eq('id',eventId).single();if(owner.error)throw owner.error;await requests.leaveEvent(db,c.env,user,eventId);await realtime.all(c.env,{type:'event.updated',eventId});await realtime.users(c.env,[user.id,owner.data.organizer_id],{type:'membership.changed',eventId});return c.json({ok:true})});
app.delete('/api/events/:id/members/:userId',async c=>{const db=createDb(c.env),user=await currentUser(c,db),eventId=c.req.param('id'),targetId=c.req.param('userId');await requests.removeMember(db,c.env,user,eventId,targetId);await realtime.all(c.env,{type:'event.updated',eventId});await realtime.users(c.env,[user.id,targetId],{type:'membership.changed',eventId});return c.json({ok:true})});
app.post('/api/events/:id/cover',async c=>{const db=createDb(c.env),user=await currentUser(c,db),eventId=c.req.param('id');await events.requireOwner(db,user,eventId);const form=await c.req.formData(),file=form.get('file');if(!(file instanceof File))throw new HttpError(422,'Файл не выбран.');if(file.size>5*1024*1024)throw new HttpError(413,'Максимальный размер изображения — 5 МБ.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new HttpError(415,'Допустимы JPG, PNG и WebP.');const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg',path=`${user.id}/${eventId}/${Date.now()}.${ext}`;const up=await db.storage.from('event-media').upload(path,await file.arrayBuffer(),{contentType:file.type,upsert:false,cacheControl:'3600'});if(up.error)throw up.error;const url=db.storage.from('event-media').getPublicUrl(path).data.publicUrl;const update=await db.from('events').update({cover_url:url}).eq('id',eventId).eq('organizer_id',user.id);if(update.error)throw update.error;await realtime.all(c.env,{type:'event.updated',eventId});return c.json({ok:true,coverUrl:url})});

app.get('/api/requests',async c=>{const db=createDb(c.env),user=await currentUser(c,db),direction=c.req.query('direction')==='outgoing'?'outgoing':'incoming';return c.json({ok:true,requests:await requests.listRequests(db,user,direction)})});
app.get('/api/requests/:id',async c=>{const db=createDb(c.env),user=await currentUser(c,db);return c.json({ok:true,request:await requests.requestDetail(db,user,c.req.param('id'))})});
app.post('/api/requests/:id/resolve',async c=>{const db=createDb(c.env),user=await currentUser(c,db),input=await body<any>(c,resolveSchema),requestId=c.req.param('id');const before=await db.from('event_requests').select('event_id,user_id').eq('id',requestId).single();if(before.error)throw before.error;const status=await requests.resolveRequest(db,c.env,user,requestId,input.decision);await realtime.users(c.env,[user.id,before.data.user_id],{type:'request.changed',eventId:before.data.event_id,requestId});await realtime.all(c.env,{type:'event.updated',eventId:before.data.event_id});if(input.decision==='accepted')await realtime.users(c.env,[user.id,before.data.user_id],{type:'membership.changed',eventId:before.data.event_id});return c.json({ok:true,status})});

app.get('/api/chats',async c=>{const db=createDb(c.env),user=await currentUser(c,db);return c.json({ok:true,chats:await chat.chats(db,user)})});
app.get('/api/chats/:eventId/messages',async c=>{const db=createDb(c.env),user=await currentUser(c,db),eventId=c.req.param('eventId');const messages=await chat.messages(db,user,eventId);await realtime.users(c.env,[user.id],{type:'chat.read',eventId});return c.json({ok:true,messages})});
app.post('/api/chats/:eventId/messages',async c=>{const db=createDb(c.env),user=await currentUser(c,db),input=await body<any>(c,messageSchema),eventId=c.req.param('eventId');const message=await chat.sendMessage(db,user,eventId,input.text);const members=await db.from('event_members').select('user_id').eq('event_id',eventId);if(members.error)throw members.error;const memberIds=(members.data||[]).map((x:any)=>x.user_id);await realtime.users(c.env,memberIds,{type:'chat.message',eventId,messageId:message.id});const eventMeta=await db.from('events').select('title').eq('id',eventId).single();for(const userId of memberIds.filter((id:string)=>id!==user.id)){await notify(db,c.env,{userId,actorId:user.id,eventId,type:'chat_message',title:eventMeta.data?.title||'Новое сообщение',body:`${user.display_name}: ${String(input.text).slice(0,120)}`})}return c.json({ok:true,message},201)});
app.patch('/api/messages/:id',async c=>{const db=createDb(c.env),user=await currentUser(c,db),input=await body<any>(c,messageSchema),messageId=c.req.param('id');const meta=await db.from('messages').select('event_id').eq('id',messageId).single();if(meta.error)throw meta.error;await chat.editMessage(db,user,messageId,input.text);const members=await db.from('event_members').select('user_id').eq('event_id',meta.data.event_id);if(members.error)throw members.error;await realtime.users(c.env,(members.data||[]).map((x:any)=>x.user_id),{type:'chat.message',eventId:meta.data.event_id,messageId});return c.json({ok:true})});
app.delete('/api/messages/:id',async c=>{const db=createDb(c.env),user=await currentUser(c,db),messageId=c.req.param('id');const meta=await db.from('messages').select('event_id').eq('id',messageId).single();if(meta.error)throw meta.error;await chat.deleteMessage(db,user,messageId);const members=await db.from('event_members').select('user_id').eq('event_id',meta.data.event_id);if(members.error)throw members.error;await realtime.users(c.env,(members.data||[]).map((x:any)=>x.user_id),{type:'chat.message',eventId:meta.data.event_id,messageId});return c.json({ok:true})});

app.get('/api/favorites',async c=>{const db=createDb(c.env),user=await currentUser(c,db);return c.json({ok:true,events:await events.favorites(db,user)})});
app.post('/api/favorites/:id/toggle',async c=>{const db=createDb(c.env),user=await currentUser(c,db);return c.json({ok:true,favorite:await events.toggleFavorite(db,user,c.req.param('id'))})});
app.get('/api/profile',async c=>{const db=createDb(c.env),user=await currentUser(c,db),p=await users.profile(db,user);return c.json({ok:true,...p})});
app.get('/api/users/:id',async c=>{const db=createDb(c.env),user=await currentUser(c,db),p=await users.profile(db,user,c.req.param('id'));return c.json({ok:true,...p})});
app.patch('/api/profile',async c=>{const db=createDb(c.env),user=await currentUser(c,db),input=await body<any>(c,profileSchema);const updated=await users.updateProfile(db,user,input);await realtime.users(c.env,[user.id],{type:'profile.changed'});return c.json({ok:true,user:updated})});
app.get('/api/notifications',async c=>{const db=createDb(c.env),user=await currentUser(c,db);return c.json({ok:true,notifications:await users.notifications(db,user)})});
app.post('/api/notifications/:id/read',async c=>{const db=createDb(c.env),user=await currentUser(c,db);await users.readNotification(db,user,c.req.param('id'));return c.json({ok:true})});
app.post('/api/reports',async c=>{const db=createDb(c.env),user=await currentUser(c,db),input=await body<any>(c,reportSchema);await users.report(db,user,input);return c.json({ok:true},201)});

// Transitional compatibility for cached V14 clients. New V15 uses the REST routes above.
app.post('/api',async c=>{const b:any=await c.req.json().catch(()=>({}));const db=createDb(c.env);if(b.action==='events'){const u=await currentUser(c,db,false);return c.json({ok:true,events:await events.publicEvents(db,u)})}if(b.action==='public_config')return c.json({ok:true,config:{appUrl:c.env.APP_URL||'',mapEngine:'maplibre-osm'}});const u=await currentUser(c,db,true);switch(b.action){case'session':{const bot=(c.env.TELEGRAM_BOT_USERNAME||'').replace(/^@/,'');return c.json({ok:true,user:userDto(u),stats:{myEvents:0,pendingRequests:0,unreadNotifications:0},config:{appLinkBase:bot?`https://t.me/${bot}/${c.env.TELEGRAM_APP_SHORT_NAME||'app'}`:'',appUrl:c.env.APP_URL||'',mapEngine:'maplibre-osm'}})}case'event':return c.json({ok:true,event:await events.oneEvent(db,u,String(b.id||''))});case'my_events':return c.json({ok:true,events:await events.myEvents(db,u)});case'create_event':return c.json({ok:true,event:await events.createEvent(db,u,b)},201);case'join_event':return c.json({ok:true,request:await requests.joinEvent(db,c.env,u,String(b.eventId||''),String(b.note||''))});case'requests':return c.json({ok:true,requests:await requests.listRequests(db,u,b.direction==='outgoing'?'outgoing':'incoming')});case'request_detail':return c.json({ok:true,request:await requests.requestDetail(db,u,String(b.requestId||''))});case'resolve_request':return c.json({ok:true,status:await requests.resolveRequest(db,c.env,u,String(b.requestId||''),b.decision)});case'chats':return c.json({ok:true,chats:await chat.chats(db,u)});case'messages':return c.json({ok:true,messages:await chat.messages(db,u,String(b.eventId||''))});case'send_message':{const eventId=String(b.eventId||''),message=await chat.sendMessage(db,u,eventId,String(b.text||'')),members=await db.from('event_members').select('user_id').eq('event_id',eventId);if(members.error)throw members.error;const memberIds=(members.data||[]).map((x:any)=>x.user_id);await realtime.users(c.env,memberIds,{type:'chat.message',eventId,messageId:message.id});const eventMeta=await db.from('events').select('title').eq('id',eventId).single();for(const userId of memberIds.filter((id:string)=>id!==u.id)){await notify(db,c.env,{userId,actorId:u.id,eventId,type:'chat_message',title:eventMeta.data?.title||'Новое сообщение',body:`${u.display_name}: ${String(b.text||'').slice(0,120)}`})}return c.json({ok:true,message},201)};default:throw new HttpError(404,'Неизвестное действие API.')}});

app.all('*',c=>c.env.ASSETS.fetch(c.req.raw));
export default app;
